FROM jmiahman/mageia-rpmbuilder-x86_64:latest
MAINTAINER JMiahMan <JMiahMan@Unity-Linux.org>
RUN dnf -y install 'dnf-command(config-manager)'
RUN dnf config-manager --set-disabled mageia-x86_64 --set-disabled updates-x86_64
RUN dnf config-manager --set-enabled cauldron-x86_64-nonfree cauldron-x86_64-nonfree
RUN dnf clean all
RUN mkdir -p /etc/yum.repos.d/
ADD https://raw.githubusercontent.com/unity-linux/unity-repos/master/Unity-Linux-mageia.repo /etc/yum.repos.d/Unity-Linux-mageia.repo
ADD https://raw.githubusercontent.com/unity-linux/unity-repos/master/RPM-GPG-KEY-Unity /etc/pki/rpm-gpg/RPM-GPG-KEY-Unity
RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-Unity
RUN dnf -y reinstall --setopt=install_weak_deps=False systemd
RUN dnf -y install --setopt=install_weak_deps=False systemd grub2 wget curl openssh-clients openssh-server dhcp-client cloud-init cloud-utils*
RUN dnf -y install --setopt=install_weak_deps=False dnf-plugins-core mock mgarepo rpmdevtools rpm-sign cracklib-dicts rpmlint intltool
RUN dnf update -y
RUN dnf clean all
RUN useradd live
RUN echo "config_opts['cache_topdir'] = '/rpmbuild/cache'" >> /etc/mock/site-defaults.cfg
RUN echo "root:Unity!" | chpasswd
RUN passwd -d root
VOLUME [ "/rpmbuild" ]
VOLUME [ "/sys/fs/cgroup" ]
CMD ["/bin/bash"]
